use super::*;

impl CaseBuilderService {
    pub async fn ensure_indexes(&self) -> ApiResult<()> {
        let statements = [
            "CREATE CONSTRAINT casebuilder_matter_id IF NOT EXISTS FOR (n:Matter) REQUIRE n.matter_id IS UNIQUE",
            "CREATE INDEX casebuilder_matter_owner IF NOT EXISTS FOR (n:Matter) ON (n.owner_subject)",
            "CREATE CONSTRAINT casebuilder_user_settings_id IF NOT EXISTS FOR (n:CaseBuilderUserSettings) REQUIRE n.settings_id IS UNIQUE",
            "CREATE INDEX casebuilder_user_settings_subject IF NOT EXISTS FOR (n:CaseBuilderUserSettings) ON (n.subject)",
            "CREATE CONSTRAINT casebuilder_matter_settings_matter IF NOT EXISTS FOR (n:CaseBuilderMatterSettings) REQUIRE n.matter_id IS UNIQUE",
            "CREATE INDEX casebuilder_matter_settings_owner IF NOT EXISTS FOR (n:CaseBuilderMatterSettings) ON (n.owner_subject)",
            "CREATE CONSTRAINT casebuilder_party_id IF NOT EXISTS FOR (n:Party) REQUIRE n.party_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_document_id IF NOT EXISTS FOR (n:CaseDocument) REQUIRE n.document_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_fact_id IF NOT EXISTS FOR (n:Fact) REQUIRE n.fact_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_timeline_event_id IF NOT EXISTS FOR (n:TimelineEvent) REQUIRE n.event_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_timeline_suggestion_id IF NOT EXISTS FOR (n:TimelineSuggestion) REQUIRE n.suggestion_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_timeline_agent_run_id IF NOT EXISTS FOR (n:TimelineAgentRun) REQUIRE n.agent_run_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_evidence_id IF NOT EXISTS FOR (n:Evidence) REQUIRE n.evidence_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_claim_id IF NOT EXISTS FOR (n:Claim) REQUIRE n.claim_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_defense_id IF NOT EXISTS FOR (n:Defense) REQUIRE n.defense_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_element_id IF NOT EXISTS FOR (n:Element) REQUIRE n.element_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_draft_id IF NOT EXISTS FOR (n:Draft) REQUIRE n.draft_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_draft_paragraph_id IF NOT EXISTS FOR (n:DraftParagraph) REQUIRE n.paragraph_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_deadline_instance_id IF NOT EXISTS FOR (n:DeadlineInstance) REQUIRE n.deadline_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_task_id IF NOT EXISTS FOR (n:Task) REQUIRE n.task_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_fact_check_finding_id IF NOT EXISTS FOR (n:FactCheckFinding) REQUIRE n.finding_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_citation_check_finding_id IF NOT EXISTS FOR (n:CitationCheckFinding) REQUIRE n.finding_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_object_blob_id IF NOT EXISTS FOR (n:ObjectBlob) REQUIRE n.object_blob_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_document_version_id IF NOT EXISTS FOR (n:DocumentVersion) REQUIRE n.document_version_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_ingestion_run_id IF NOT EXISTS FOR (n:IngestionRun) REQUIRE n.ingestion_run_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_source_span_id IF NOT EXISTS FOR (n:SourceSpan) REQUIRE n.source_span_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_index_run_id IF NOT EXISTS FOR (n:IndexRun) REQUIRE n.index_run_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_page_id IF NOT EXISTS FOR (n:Page) REQUIRE n.page_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_text_chunk_id IF NOT EXISTS FOR (n:TextChunk) REQUIRE n.text_chunk_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_evidence_span_id IF NOT EXISTS FOR (n:EvidenceSpan) REQUIRE n.evidence_span_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_entity_mention_id IF NOT EXISTS FOR (n:EntityMention) REQUIRE n.entity_mention_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_case_entity_id IF NOT EXISTS FOR (n:CaseEntity) REQUIRE n.entity_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_markdown_ast_document_id IF NOT EXISTS FOR (n:MarkdownAstDocument) REQUIRE n.markdown_ast_document_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_markdown_ast_node_id IF NOT EXISTS FOR (n:MarkdownAstNode) REQUIRE n.markdown_ast_node_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_markdown_semantic_unit_id IF NOT EXISTS FOR (n:MarkdownSemanticUnit) REQUIRE n.semantic_unit_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_search_index_record_id IF NOT EXISTS FOR (n:SearchIndexRecord) REQUIRE n.search_index_record_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_embedding_run_id IF NOT EXISTS FOR (n:CaseBuilderEmbeddingRun) REQUIRE n.embedding_run_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_embedding_record_id IF NOT EXISTS FOR (n:CaseBuilderEmbeddingRecord) REQUIRE n.embedding_record_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_extraction_artifact_manifest_id IF NOT EXISTS FOR (n:ExtractionArtifactManifest) REQUIRE n.manifest_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_document_annotation_id IF NOT EXISTS FOR (n:DocumentAnnotation) REQUIRE n.annotation_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_transcription_job_id IF NOT EXISTS FOR (n:TranscriptionJob) REQUIRE n.transcription_job_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_transcript_segment_id IF NOT EXISTS FOR (n:TranscriptSegment) REQUIRE n.segment_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_transcript_speaker_id IF NOT EXISTS FOR (n:TranscriptSpeaker) REQUIRE n.speaker_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_transcript_review_change_id IF NOT EXISTS FOR (n:TranscriptReviewChange) REQUIRE n.review_change_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_complaint_id IF NOT EXISTS FOR (n:ComplaintDraft) REQUIRE n.complaint_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_complaint_section_id IF NOT EXISTS FOR (n:ComplaintSection) REQUIRE n.section_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_complaint_count_id IF NOT EXISTS FOR (n:ComplaintCount) REQUIRE n.count_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_pleading_paragraph_id IF NOT EXISTS FOR (n:PleadingParagraph) REQUIRE n.paragraph_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_pleading_sentence_id IF NOT EXISTS FOR (n:PleadingSentence) REQUIRE n.sentence_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_citation_use_id IF NOT EXISTS FOR (n:CitationUse) REQUIRE n.citation_use_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_evidence_use_id IF NOT EXISTS FOR (n:EvidenceUse) REQUIRE n.evidence_use_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_exhibit_reference_id IF NOT EXISTS FOR (n:ExhibitReference) REQUIRE n.exhibit_reference_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_relief_request_id IF NOT EXISTS FOR (n:ReliefRequest) REQUIRE n.relief_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_rule_check_finding_id IF NOT EXISTS FOR (n:RuleCheckFinding) REQUIRE n.finding_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_export_artifact_id IF NOT EXISTS FOR (n:ExportArtifact) REQUIRE n.artifact_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_complaint_history_event_id IF NOT EXISTS FOR (n:ComplaintHistoryEvent) REQUIRE n.event_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_external_authority_id IF NOT EXISTS FOR (n:ExternalAuthority) REQUIRE n.canonical_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_work_product_id IF NOT EXISTS FOR (n:WorkProduct) REQUIRE n.work_product_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_work_product_block_id IF NOT EXISTS FOR (n:WorkProductBlock) REQUIRE n.block_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_work_product_mark_id IF NOT EXISTS FOR (n:WorkProductMark) REQUIRE n.mark_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_work_product_anchor_id IF NOT EXISTS FOR (n:WorkProductAnchor) REQUIRE n.anchor_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_work_product_finding_id IF NOT EXISTS FOR (n:WorkProductFinding) REQUIRE n.finding_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_work_product_artifact_id IF NOT EXISTS FOR (n:WorkProductArtifact) REQUIRE n.artifact_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_work_product_history_event_id IF NOT EXISTS FOR (n:WorkProductHistoryEvent) REQUIRE n.event_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_change_set_id IF NOT EXISTS FOR (n:ChangeSet) REQUIRE n.change_set_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_version_snapshot_id IF NOT EXISTS FOR (n:VersionSnapshot) REQUIRE n.snapshot_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_snapshot_manifest_id IF NOT EXISTS FOR (n:SnapshotManifest) REQUIRE n.manifest_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_snapshot_entity_state_id IF NOT EXISTS FOR (n:SnapshotEntityState) REQUIRE n.entity_state_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_version_change_id IF NOT EXISTS FOR (n:VersionChange) REQUIRE n.change_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_version_branch_id IF NOT EXISTS FOR (n:VersionBranch) REQUIRE n.branch_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_legal_support_use_id IF NOT EXISTS FOR (n:LegalSupportUse) REQUIRE n.support_use_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_fact_use_id IF NOT EXISTS FOR (n:FactUse) REQUIRE n.support_use_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_authority_use_id IF NOT EXISTS FOR (n:AuthorityUse) REQUIRE n.support_use_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_element_support_id IF NOT EXISTS FOR (n:ElementSupport) REQUIRE n.support_use_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_ai_edit_audit_id IF NOT EXISTS FOR (n:AIEditAudit) REQUIRE n.ai_audit_id IS UNIQUE",
            "CREATE CONSTRAINT casebuilder_milestone_id IF NOT EXISTS FOR (n:Milestone) REQUIRE n.milestone_id IS UNIQUE",
            "CREATE INDEX casebuilder_document_matter IF NOT EXISTS FOR (n:CaseDocument) ON (n.matter_id)",
            "CREATE INDEX casebuilder_document_processing IF NOT EXISTS FOR (n:CaseDocument) ON (n.matter_id, n.processing_status)",
            "CREATE INDEX casebuilder_fact_matter IF NOT EXISTS FOR (n:Fact) ON (n.matter_id)",
            "CREATE INDEX casebuilder_timeline_suggestion_matter IF NOT EXISTS FOR (n:TimelineSuggestion) ON (n.matter_id, n.status)",
            "CREATE INDEX casebuilder_timeline_suggestion_document IF NOT EXISTS FOR (n:TimelineSuggestion) ON (n.source_document_id, n.status)",
            "CREATE INDEX casebuilder_timeline_agent_run_matter IF NOT EXISTS FOR (n:TimelineAgentRun) ON (n.matter_id, n.status)",
            "CREATE INDEX casebuilder_claim_matter IF NOT EXISTS FOR (n:Claim) ON (n.matter_id)",
            "CREATE INDEX casebuilder_draft_matter IF NOT EXISTS FOR (n:Draft) ON (n.matter_id)",
            "CREATE INDEX casebuilder_document_version_matter IF NOT EXISTS FOR (n:DocumentVersion) ON (n.matter_id)",
            "CREATE INDEX casebuilder_ingestion_run_matter IF NOT EXISTS FOR (n:IngestionRun) ON (n.matter_id)",
            "CREATE INDEX casebuilder_source_span_matter IF NOT EXISTS FOR (n:SourceSpan) ON (n.matter_id)",
            "CREATE INDEX casebuilder_source_span_document IF NOT EXISTS FOR (n:SourceSpan) ON (n.document_id)",
            "CREATE INDEX casebuilder_index_run_matter IF NOT EXISTS FOR (n:IndexRun) ON (n.matter_id, n.status)",
            "CREATE INDEX casebuilder_page_document IF NOT EXISTS FOR (n:Page) ON (n.document_id, n.page_number)",
            "CREATE INDEX casebuilder_text_chunk_document IF NOT EXISTS FOR (n:TextChunk) ON (n.document_id, n.ordinal)",
            "CREATE INDEX casebuilder_text_chunk_status IF NOT EXISTS FOR (n:TextChunk) ON (n.status)",
            "CREATE INDEX casebuilder_evidence_span_document IF NOT EXISTS FOR (n:EvidenceSpan) ON (n.document_id, n.review_status)",
            "CREATE INDEX casebuilder_entity_mention_document IF NOT EXISTS FOR (n:EntityMention) ON (n.document_id, n.entity_type)",
            "CREATE INDEX casebuilder_case_entity_matter IF NOT EXISTS FOR (n:CaseEntity) ON (n.matter_id, n.entity_type)",
            "CREATE INDEX casebuilder_markdown_ast_document_document IF NOT EXISTS FOR (n:MarkdownAstDocument) ON (n.document_id, n.status)",
            "CREATE INDEX casebuilder_markdown_ast_node_document IF NOT EXISTS FOR (n:MarkdownAstNode) ON (n.document_id, n.ordinal)",
            "CREATE INDEX casebuilder_markdown_ast_node_kind IF NOT EXISTS FOR (n:MarkdownAstNode) ON (n.node_kind)",
            "CREATE INDEX casebuilder_markdown_ast_node_section IF NOT EXISTS FOR (n:MarkdownAstNode) ON (n.document_id, n.section_path)",
            "CREATE INDEX casebuilder_markdown_semantic_unit_document IF NOT EXISTS FOR (n:MarkdownSemanticUnit) ON (n.document_id, n.unit_kind)",
            "CREATE INDEX casebuilder_markdown_semantic_unit_role IF NOT EXISTS FOR (n:MarkdownSemanticUnit) ON (n.semantic_role)",
            "CREATE INDEX casebuilder_search_index_record_document IF NOT EXISTS FOR (n:SearchIndexRecord) ON (n.document_id, n.status)",
            "CREATE INDEX casebuilder_embedding_run_matter IF NOT EXISTS FOR (n:CaseBuilderEmbeddingRun) ON (n.matter_id, n.status)",
            "CREATE INDEX casebuilder_embedding_record_matter IF NOT EXISTS FOR (n:CaseBuilderEmbeddingRecord) ON (n.matter_id, n.target_kind, n.status)",
            "CREATE INDEX casebuilder_embedding_record_document IF NOT EXISTS FOR (n:CaseBuilderEmbeddingRecord) ON (n.document_id, n.stale)",
            "CREATE INDEX casebuilder_extraction_artifact_manifest_document IF NOT EXISTS FOR (n:ExtractionArtifactManifest) ON (n.document_id)",
            "CREATE INDEX casebuilder_document_annotation_document IF NOT EXISTS FOR (n:DocumentAnnotation) ON (n.document_id, n.status)",
            "CREATE INDEX casebuilder_transcription_job_document IF NOT EXISTS FOR (n:TranscriptionJob) ON (n.document_id, n.status)",
            "CREATE INDEX casebuilder_transcription_job_provider IF NOT EXISTS FOR (n:TranscriptionJob) ON (n.provider_transcript_id)",
            "CREATE INDEX casebuilder_transcript_segment_job IF NOT EXISTS FOR (n:TranscriptSegment) ON (n.transcription_job_id, n.ordinal)",
            "CREATE INDEX casebuilder_transcript_speaker_job IF NOT EXISTS FOR (n:TranscriptSpeaker) ON (n.transcription_job_id)",
            "CREATE INDEX casebuilder_complaint_matter IF NOT EXISTS FOR (n:ComplaintDraft) ON (n.matter_id)",
            "CREATE INDEX casebuilder_complaint_status IF NOT EXISTS FOR (n:ComplaintDraft) ON (n.status)",
            "CREATE INDEX casebuilder_pleading_paragraph_complaint IF NOT EXISTS FOR (n:PleadingParagraph) ON (n.complaint_id)",
            "CREATE INDEX casebuilder_rule_check_finding_complaint IF NOT EXISTS FOR (n:RuleCheckFinding) ON (n.complaint_id, n.status)",
            "CREATE INDEX casebuilder_export_artifact_complaint IF NOT EXISTS FOR (n:ExportArtifact) ON (n.complaint_id, n.status)",
            "CREATE INDEX casebuilder_work_product_matter IF NOT EXISTS FOR (n:WorkProduct) ON (n.matter_id)",
            "CREATE INDEX casebuilder_work_product_type IF NOT EXISTS FOR (n:WorkProduct) ON (n.product_type, n.status)",
            "CREATE INDEX casebuilder_work_product_block_parent IF NOT EXISTS FOR (n:WorkProductBlock) ON (n.work_product_id, n.role)",
            "CREATE INDEX casebuilder_work_product_block_matter IF NOT EXISTS FOR (n:WorkProductBlock) ON (n.matter_id, n.block_type)",
            "CREATE INDEX casebuilder_work_product_finding_status IF NOT EXISTS FOR (n:WorkProductFinding) ON (n.work_product_id, n.status)",
            "CREATE INDEX casebuilder_work_product_artifact_status IF NOT EXISTS FOR (n:WorkProductArtifact) ON (n.work_product_id, n.status)",
            "CREATE INDEX casebuilder_change_set_subject IF NOT EXISTS FOR (n:ChangeSet) ON (n.subject_id, n.created_at)",
            "CREATE INDEX casebuilder_version_snapshot_subject IF NOT EXISTS FOR (n:VersionSnapshot) ON (n.subject_id, n.sequence_number)",
            "CREATE INDEX casebuilder_version_branch_subject IF NOT EXISTS FOR (n:VersionBranch) ON (n.subject_id, n.branch_type)",
            "CREATE INDEX casebuilder_version_change_subject IF NOT EXISTS FOR (n:VersionChange) ON (n.subject_id, n.target_type)",
            "CREATE INDEX casebuilder_legal_support_use_subject IF NOT EXISTS FOR (n:LegalSupportUse) ON (n.subject_id, n.target_id)",
            "CREATE INDEX casebuilder_ai_edit_audit_subject IF NOT EXISTS FOR (n:AIEditAudit) ON (n.subject_id, n.created_at)",
            "CREATE FULLTEXT INDEX casebuilder_fact_fulltext IF NOT EXISTS FOR (n:Fact) ON EACH [n.text, n.statement]",
            "CREATE FULLTEXT INDEX casebuilder_document_fulltext IF NOT EXISTS FOR (n:CaseDocument) ON EACH [n.filename, n.title, n.summary, n.extracted_text]",
            "CREATE FULLTEXT INDEX casebuilder_text_chunk_fulltext IF NOT EXISTS FOR (n:TextChunk) ON EACH [n.text_excerpt]",
            "CREATE FULLTEXT INDEX casebuilder_markdown_ast_node_fulltext IF NOT EXISTS FOR (n:MarkdownAstNode) ON EACH [n.text_excerpt, n.structure_path]",
            "CREATE FULLTEXT INDEX casebuilder_markdown_semantic_unit_fulltext IF NOT EXISTS FOR (n:MarkdownSemanticUnit) ON EACH [n.canonical_label, n.section_path, n.structure_path]",
            "CREATE FULLTEXT INDEX casebuilder_complaint_fulltext IF NOT EXISTS FOR (n:ComplaintDraft|PleadingParagraph|ComplaintCount) ON EACH [n.title, n.text, n.legal_theory]",
            "CREATE FULLTEXT INDEX casebuilder_work_product_fulltext IF NOT EXISTS FOR (n:WorkProduct|WorkProductBlock) ON EACH [n.title, n.text, n.product_type]",
            "CREATE VECTOR INDEX casebuilder_markdown_embedding_1024 IF NOT EXISTS FOR (n:CaseBuilderEmbeddingRecord) ON n.embedding OPTIONS {indexConfig: {`vector.dimensions`: 1024, `vector.similarity_function`: 'cosine'}}",
        ];

        for statement in statements {
            self.neo4j.run_rows(query(statement)).await?;
        }

        Ok(())
    }
}
